version: '3'

services:
  db:
    image: postgres
    # environment: 
    #   POSTGRES_DB: "db"
    #   POSTGRES_PASSWORD: "qwerty"
    env_file: 
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  medicar:
    build: ./source
    command: python manage.py runserver_plus 0.0.0.0:8000
    env_file: 
      - .env
    volumes:
      - ./source/:/usr/src/source/
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: