version: '3'

services:
  db:
    image: postgres
    # environment: 
    #   POSTGRES_DB: "db"
    #   POSTGRES_PASSWORD: "qwerty"
    env_file: 
      - .env
  medicar:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file: 
      - .env
    volumes:
      - .:/source
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  source: