# Generated by Django 3.0.3 on 2020-06-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='agenda',
        ),
        migrations.AddField(
            model_name='agenda',
            name='horarios',
            field=models.ManyToManyField(to='agenda.Horario', verbose_name='Horarios Disponiveis'),
        ),
    ]
