version: '3'

services:
  db:
    image: postgres
    # environment: 
    #   POSTGRES_DB: "db"
    #   POSTGRES_PASSWORD: "qwerty"
    env_file: 
      - ./BackEnd/env.prod.db 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  medicar:
    build: 
      context: ./source
      dockerfile: Dockerfile.prod
    command: gunicorn medicar.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/source/medicar/staticfiles
    env_file: 
      - .env.prod
    expose:
        - 8000
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/source/medicar/staticfiles
    ports:
      - 80:80
    depends_on:
      - medicar

      
volumes:
  postgres_data:
  static_volume: